language: node_js
node_js:
- '12'
script: npm run lint && npm test
before_deploy: npm run build && cd dist
deploy:
  provider: npm
  email: leewayzhang@outlook.com
  skip_cleanup: true
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: true
    branch: master
  tag: latest
