language: node_js
node_js:
- '12'
script: npm run lint && npm test
before_deploy: npm run build && cd dist
deploy:
  provider: npm
  email: leewayzhang@outlook.com
  skip_cleanup: true
  api_key:
    secure: Xa1StG0ygO+R4Z1jdpxUHUlhY1r12ejPPVHAMY9m8l1gi0GKXY1aruEM+kcbznSDUELyvawiwYe7Mt6nAdxEVIAePSYVT2SiSKRIIk+TqLqkoHNcusDgMbE/L+tQvHjPz4Hc1w/uzbfnad/K686gWqcxz1WqdhbeGb2YSFHUH0OOYPg2m3UG/wKEFtz/5Q3+CnntJPijFLadmTBk/WcRAtMa0x3PYWTn5y7aPt3Tu4FT6kySDyRyxCt2g7yCUZiVjK2cur8PS1Ffd1RHxFyIWj/1uTjLmZAGYaVl5Eurau6JOM+j0I3xRPK/JO46RYHrodxScKyt+gQ2FUrvZnY1HbthjGuKDoB4CnqmWlQoXRLKeFE7XkXH0jcXvAniqIWksY8zEYQ5ib9kWdiVWD8XIqJlg+jrZyei6YPRFzGduevZpFh/ujFBltiR/1S+gYpDE42lsm0rk8vh0Hy3QYHvYCtSHUFzAzhKOFHNq84Gapz1YJQG9kN4gQoSX/y6P92qjqyBMoBCnGuyMrgmTEVAGEHFAeVfT17L6ZmkGSGcotTwy4MtXs6SvEfx++hm5CgIvPcnJqo0qcBkw/SmwyyipsiJcGPadfuNXVTqGCvCLIWaB+yyzDMgg09paNnjiLSm7WoDzZwo8vAx3y2WN7oHe0e2YhvW2dd9QV1Lr7SCFu4=
  on:
    tags: true
    branch: master
  tag: latest
